# Generated by Django 3.0.8 on 2020-07-28 09:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# config.migrations.eats.0003_auto_20200724_0729


def create_ingredients(apps, schema_editor):
    fixture = 'ingredients_data'
    call_command('loaddata', fixture, app_label='eats')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('average_food_cost', models.IntegerField(editable=False, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.FloatField(editable=False)),
                ('longitude', models.FloatField(editable=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.RunPython(
            code=create_ingredients,
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/dishes/')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredients', models.ManyToManyField(to='eats.Ingredient')),
                ('calories_value', models.IntegerField(default=0, editable=False)),
                ('institution', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='eats.Institution')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='working_hours_begin',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='working_hours_end',
            field=models.TimeField(default=datetime.time(22, 0)),
            preserve_default=False,
        ),
    ]
