# Generated by Django 3.0.8 on 2020-07-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eats', '0001_squashed_0009_auto_20200728_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eats.Institution'),
        ),
    ]
